version: '3.8'

services:
  apache-php:
    build: ./apache-php
    ports:
      - "8080:80"
    volumes:
      - ./apache-php/www:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=espuser
      - MYSQL_PASSWORD=esppass
      - MYSQL_DATABASE=espdata

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: espdata
      MYSQL_USER: espuser
      MYSQL_PASSWORD: esppass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
