function [fitresult, gof] = createFit1(Tiempo, Z)
%CREATEFIT1(TIEMPO,Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: Tiempo
%      Y Output: Z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Mar-2025 17:10:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Tiempo, Z );

% Set up fittype and options.
ft = fittype( 'fourier8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5.50705735699894];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Z vs. Tiempo', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Tiempo', 'Interpreter', 'none' );
ylabel( 'Z', 'Interpreter', 'none' );
grid on


